# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PXQTJKlIIwhFah8o2_zNUTwXUScJ1PA6
"""

import matplotlib.pyplot as plt

n = int(input("N:"))
seed_value = int(input("Seed No:"))

random_number = []
seed_list = []


count = 0 

while True: 

  
  num_sq = seed_value ** 2
  num = num_sq % 10 ** (n + (n/2))
  num = num / 10 ** ( n /2)

  updated_seed = int (num) # to store whole value 

  num = int( num) / 10 ** (n)  # convert to decimal 

  

  if updated_seed in seed_list: 
      break
  
  count +=1 # count increses

  random_number.append(num)  # store in list 

  print("random number",num)   # print random number 

  seed_value = updated_seed  # update the seed value 

  #print("seed",seed_value)
  seed_list.append(seed_value)
  

  
  
  
  

print("Count:", count)
print(len(random_number))
plt.hist(random_number)
plt.show()